theme: jekyll-theme-cayman
title: [Comment Insight]
description: [Easy to Statistics&Count&Clean the comments in your SourceCode. 源代码注释统计&清理工具]

show_downloads: true

url: https://CommentInsight.github.io

github:
  is_project_page: true
  zip_url: https://github.com/CommentInsight/CommentInsight/releases
  tar_url: https://gitee.com/nnfish/CommentInsight/releases/
  repository_url: https://github.com/CommentInsight/CommentInsight
